export const bookList = [
    {
      id: 1,
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      year: 1925,
      price: 10.99,
      star: 4.5,
      isFavourite: true,
      img: "https://placekitten.com/200/300",
    },
    {
      id: 2,
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      year: 1960,
      price: 12.99,
      star: 4.8,
      isFavourite: false,
      img: "./assets/book.png",
    },
    {
      id: 3,
      title: "1984",
      author: "George Orwell",
      year: 1949,
      price: 9.99,
      star: 4.7,
      isFavourite: true,
      img: "./assets/book.png",
    },
    {
      id: 4,
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      year: 1951,
      price: 11.99,
      star: 4.2,
      isFavourite: false,
      img: "./assets/book.png",
    },
    {
      id: 5,
      title: "Harry Potter",
      author: "J.K. Rowling",
      year: 1997,
      price: 14.99,
      star: 4.9,
      isFavourite: true,
      img: "./assets/book.png",
    },
    {
      id: 6,
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      year: 1937,
      price: 13.99,
      star: 4.6,
      isFavourite: false,
      img: "./assets/book.png",
    },
    {
      id: 7,
      title: "The Lord of the Rings",
      author: "J.R.R. Tolkien",
      year: 1954,
      price: 18.99,
      star: 4.7,
      isFavourite: true,
      img: "./assets/book.png",
    },
    {
      id: 8,
      title: "Pride and Prejudice",
      author: "Jane Austen",
      year: 1813,
      price: 8.99,
      star: 4.4,
      isFavourite: false,
      img: "./assets/book.png",
    },
    {
      id: 9,
      title: "The Alchemist",
      author: "Paulo Coelho",
      year: 1988,
      price: 15.99,
      star: 4.6,
      isFavourite: true,
      img: "./assets/book.png",
    },
    {
      id: 10,
      title: "The Da Vinci Code",
      author: "Dan Brown",
      year: 2003,
      price: 16.99,
      star: 4.3,
      isFavourite: false,
      img: "./assets/book.png",
    },
  ];
  